steps:

# CPU

- id: 'build'
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --rm
  - --no-cache
  - --file=Dockerfile
  - --build-arg=ncpus=32
  - --tag=gcr.io/$PROJECT_ID/rstats-build:ci-pretest
  - --tag=gcr.io/$PROJECT_ID/rcran-build:staging
  - --tag=gcr.io/kaggle-images/rstats
  - .

- id: 'intermediate-push'
  waitFor: ['build']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/rcran-build:ci-pretest

- id: 'test'
  waitFor: ['build']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ./test


# GPU

# - id: 'build-gpu'
#   waitFor: ['-']
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#   - build
#   - --rm
#   - --no-cache
#   - --file=gpu.Dockerfile
#   - --tag=gcr.io/$PROJECT_ID/rstats-gpu-build:ci-pretest
#   - --tag=gcr.io/kaggle-private-byod/rstats
#   - .

# - id: 'intermediate-push-gpu'
#   waitFor: ['build-gpu']
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#   - push
#   - gcr.io/$PROJECT_ID/rstats-gpu-build:ci-pretest

# - id: 'test-gpu'
#   waitFor: ['build-gpu']
#   name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     ./test --gpu

# images:
#   - gcr.io/$PROJECT_ID/rcran-build:staging
#   - gcr.io/$PROJECT_ID/rstats-gpu-build:staging
#   - gcr.io/kaggle-images/rstats
#   - gcr.io/kaggle-private-byod/rstats

options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 1000 # Max disk size. Gives more IOPS.

timeout: 86400s

tags: ['rstats']